In [1]:
import torch
import torch.nn as nn

In [ ]:
torch.manual_seed(123)
bacth_example = torch.randn(2, 5) #A
print(bacth_example)
layer = nn.Sequential(nn.Linear(5, 6), nn.ReLU()) #ReLU means rectified Linear Unit, it ia an activation function used in Deep Learning and Neural Networks
#nn.Linear(5, 6) specifies that this layer takes 5 inputs and returns 6 outputs.
out = layer(bacth_example)
#output of the input layer in sequential order beacuse of the nn.Sequential() applied
print(out)

tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969],
        [ 0.2093, -0.9724, -0.7550,  0.3239, -0.1085]])
tensor([[0.2260, 0.3470, 0.0000, 0.2216, 0.0000, 0.0000],
        [0.2133, 0.2394, 0.0000, 0.5198, 0.3297, 0.0000]],
       grad_fn=<ReluBackward0>)


Layer normalization

In [6]:
mean = out.mean(dim=-1, keepdim=True) #dim=-1 because we want to tke the mean on the column axis
#Keepdim is set to True so that our outputs returns a matrix instead of a 2- vector
var = out.var(dim=-1, keepdim=True)
print(f"Mean:\n {mean}")
print(f"Variance\n: {var}")

Mean:
 tensor([[0.1324],
        [0.2170]], grad_fn=<MeanBackward1>)
Variance
: tensor([[0.0231],
        [0.0398]], grad_fn=<VarBackward0>)


In [7]:
out_norm = (out-mean) / torch.sqrt(var)
mean = out_norm.mean(dim=-1, keepdim=True)
var = out_norm.var(dim=-1, keepdim=True)
print(f"Normalized layer outputs\n: {out_norm}")
print(f"Mean:\n {mean}")
print(f"Variance\n: {var}")

Normalized layer outputs
: tensor([[ 0.6159,  1.4126, -0.8719,  0.5872, -0.8719, -0.8719],
        [-0.0189,  0.1121, -1.0876,  1.5173,  0.5647, -1.0876]],
       grad_fn=<DivBackward0>)
Mean:
 tensor([[9.9341e-09],
        [0.0000e+00]], grad_fn=<MeanBackward1>)
Variance
: tensor([[1.0000],
        [1.0000]], grad_fn=<VarBackward0>)


To improve the readability of our outputs, we will turn off the scientific mode of the Pytorch library

In [8]:
torch.set_printoptions(sci_mode=False)
print(f"Mean:\n {mean}")
print(f"Variance\n: {var}")

Mean:
 tensor([[    0.0000],
        [    0.0000]], grad_fn=<MeanBackward1>)
Variance
: tensor([[1.0000],
        [1.0000]], grad_fn=<VarBackward0>)


Create a class for LayerNormalization

In [9]:
class LayerNorm(nn.Module): #setting the LayerNormalization class as a subclass of the nn.Module module
    def __init__(self, emb_dim): #defines the input fo the Layer Normalization class, 'dimension of the emdedding_vector'
        super().__init__()
        self.eps = 1e-5 #a small variable epislum to prevent division by zero during normalization
        self.scale = nn.Parameter(torch.ones(emb_dim))
        self.shift = nn.Parameter(torch.zeros(emb_dim))

    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var = c.var(dim=-1, keepdim=True, unbiased=False)
        norm_x = (x - mean) / torch.sqrt(var + self.eps)
        return self.scale * norm_x + self.shift

The scale and the shift variables are two trainable paramters of the same dimension as the input that the LLM automatically adjusts durng the training to improve the model's performance on its training task